stages:
  ingestion:
    cmd: python src/stages/data_ingestion.py
    deps:
      - src/stages/data_ingestion.py
      - Dataset/retail_store_inventory.csv
      - config/config.yaml
    outs:
      - data/raw/raw.csv
  
  preprocessing:
    cmd: python src/stages/data_preprocessing.py
    deps:
      - src/stages/data_preprocessing.py
      - data/raw/raw.csv
      - config/config.yaml
    outs:
      - data/processed/processed.csv
      - models/scaler.joblib

  train:
    cmd: python src/stages/model_training.py
    deps:
      - src/stages/model_training.py
      - data/processed/processed.csv
      - config/config.yaml
    outs:
      - models/xgboost_model.joblib
      - models/lightgbm_model.joblib
    metrics:
      - metrics.json:
          cache: false

  register:
    cmd: python src/stages/model_register.py && echo registration_complete > models/register.done
    deps:
      - src/stages/model_register.py
      - metrics.json
    outs:
      - models/register.done

  promotion:
    cmd: python src/stages/model_promotion.py && echo promotion_complete > models/promotion.done
    deps:
      - src/stages/model_promotion.py
      - data/processed/processed.csv
      - models/register.done
    outs:
      - models/promotion.done

  batch_prediction:
    cmd: python src/stages/batch_inference.py
    deps:
      - src/stages/batch_inference.py
      - src/models/forecaster.py
      - data/processed/processed.csv
      - models/promotion.done
    outs:
      - data/forecasts/batch_results.json
